<!-- component -->
<div
    class="lg:px-24 lg:py-24 md:py-20 md:px-44 px-4 py-24 items-center flex justify-center flex-col-reverse lg:flex-row md:gap-28 gap-16">
    <div class="xl:pt-24 w-full xl:w-1/2 relative pb-12 lg:pb-0">
        <div class="relative">
            <div class="absolute">
                <div class="">
                    <h1 class="my-2 p-3 bg-gray-950 text-white drop-shadow-2xl font-bold text-2xl">
                        Úgy tűnik, megtaláltad a
                        ajtó a nagy semmihez!
                    </h1>
                    <p class="my-2 p-2 bg-gray-950 text-white drop-shadow-2xl">Sajnálom az esetet! Kérjük, látogasson el
                        főoldalra. <a class="text-yellow-500 font-extrabold" href="/">Vissza</a></p>
                </div>
            </div>
            <div>
                <img src="https://i.ibb.co/G9DC8S0/404-2.png" alt=""/>
            </div>
        </div>
    </div>
    <div>
        <img src="https://i.ibb.co/ck1SGFJ/Group.png" alt=""/>
    </div>
</div>